### ISSUE TITLE
Dragging an image around the texts causes line breaks

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Page-Builder-Sandwich#113] opened 2015-03-18 03:50 UTC
Before dragging: http://prntscr.com/6i6b1i
After dragging around: http://prntscr.com/6i6bm6

Deleting the image will not undo the results.

This problem is exclusive for centered texts.

**Comment by bfintal** [comment] 2015-03-18 04:30
Can't replicate, this was captured from Chrome http://www.screencast-o-matic.com/watch/coeFfUesnA

Same behavior with Firefox. How was the text composed? I just typed in text then inserted the image using *Add Media*

**Comment by Gambit-Alyssa** [comment] 2015-03-18 04:32
Here is a screencast of what I did: http://screencast-o-matic.com/watch/coeFfuesnz

**Comment by bfintal** [comment] 2015-03-18 04:46
Confirmed that it also happens with Sandwich deactivated. Image dragging is native to WordPress and wasn't created by Sandwich.

http://screencast-o-matic.com/watch/coeFfEesnK

Since it happens with WP core, I'll set this to won't fix since this is a WordPress issue.

**Closed by bfintal** 2015-03-18 04:46 UTC
Labels: wontfix
